### ISSUE TITLE
areasToProtect error

### ISSUE THREAD

**Issue by hejgustav** [gaucho-matrero/altoclef#129]
When I tried copying
  "areasToProtect" : [
           {
               start: "-10, 0, -10",
               end: "10, 255, 10"
           },
           {
               start: "1000, 50, 2000",
               end: "1200, 255, 2100"
           },
      ],
from https://github.com/gaucho-matrero/altoclef/blob/main/src/main/java/adris/altoclef/Settings.java I get this error

[18:58:24] [Render thread/INFO]: [CHAT] §2§l§c[Alto Clef ERROR]Failed to read Settings at altoclef_settings.json. JSON Error Message: Unexpected character ('s' (code 115)): was expecting double-quote to start field name\n at [Source: (File); line: 83, column: 12] (through reference chain: adris.altoclef.Settings["areasToProtect"]->java.util.ArrayList[0]).\n JSON Error STACK TRACE:\n\n\nat:\nadris.altoclef.Debug.logError(Debug.java:51)\nadris.altoclef.Settings.load(Settings.java:394)\nadris.altoclef.AltoClef.reloadModSettings(AltoClef.java:299)\nadris.altoclef.commands.ReloadSettingsCommand.call(ReloadSettingsCommand.java:15)\nadris.altoclef.commandsystem.Command.run(Command.java:30)\nadris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:41)\nadris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:49)\nadris.altoclef.StaticMixinHookups.onChat(StaticMixinHookups.java:53)\nnet.minecraft.class_746.handler$zzf000$sendChatMessage(class_746.java:1271)\nnet.minecraft.class_746.method_3142(class_746.java)\nnet.minecraft.class_437.method_25425(class_437.java:376)\nnet.minecraft.class_437.method_25427(class_437.java:369)\nnet.minecraft.class_408.method_25404(class_408.java:101)\nnet.minecraft.class_309.method_1454(class_309.java:374)\nnet.minecraft.class_437.method_25412(class_437.java:490)\nnet.minecraft.class_309.method_1466(class_309.java:370)\nnet.minecraft.class_309.method_22678(class_309.java:462)\nnet.minecraft.class_1255.execute(class_1255.java:101)\nnet.minecraft.class_309.method_22676(class_309.java:462)\norg.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)\norg.lwjgl.system.JNI.invokeV(Native Method)\norg.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)\ncom.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)\nnet.minecraft.class_1041.method_15998(class_1041.java:310)\nnet.minecraft.class_310.method_1523(class_310.java:1137)\nnet.minecraft.class_310.method_1514(class_310.java:728)\nnet.minecraft.client.main.Main.main(Main.java:217)\njava.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\njava.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)\njava.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.base/java.lang.reflect.Method.invoke(Method.java:567)\nnet.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)\nnet.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)\nnet.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)\n§r
[18:58:24] [Render thread/INFO]: [STDERR]: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('s' (code 115)): was expecting double-quote to start field name
 at [Source: (File); line: 83, column: 12] (through reference chain: adris.altoclef.Settings["areasToProtect"]->java.util.ArrayList[0])
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.Settings.load(Settings.java:392)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.AltoClef.reloadModSettings(AltoClef.java:299)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commands.ReloadSettingsCommand.call(ReloadSettingsCommand.java:15)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commandsystem.Command.run(Command.java:30)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:41)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:49)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.StaticMixinHookups.onChat(StaticMixinHookups.java:53)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zzf000$sendChatMessage(class_746.java:1271)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:376)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:369)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:374)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:490)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:370)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:462)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:101)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:462)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1137)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:728)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[18:58:24] [Render thread/INFO]: [STDERR]: Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('s' (code 115)): was expecting double-quote to start field name
 at [Source: (File); line: 84, column: 17]
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleOddName(UTF8StreamJsonParser.java:2020)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1671)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:757)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[18:58:24] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
[18:58:24] [Render thread/INFO]: [STDERR]: 	... 40 more
[18:58:24] [Render thread/INFO]: [CHAT] §2§l§o[Alto Clef] §rReload successful!
[18:58:26] [Render thread/INFO]: [STDOUT]: ALTO CLEF: CHUNKS RESET
[18:58:28] [Render thread/INFO]: Stopping!

**Comment by walksanatora** [comment]
you need quotes around start and end
Fixed Json: 
"areasToProtect" : [
{
"start": "-10, 0, -10",
"end": "10, 255, 10"
},
{
"start": "1000, 50, 2000",
"end": "1200, 255, 2100"
},
],

**Comment by hejgustav** [comment]
> you need quotes around start and end Fixed Json: "areasToProtect" : [ { "start": "-10, 0, -10", "end": "10, 255, 10" }, { "start": "1000, 50, 2000", "end": "1200, 255, 2100" }, ],

I now get this error

[21:04:17] [Render thread/INFO]: [CHAT] §2§l§c[Alto Clef ERROR]Failed to read Settings at altoclef_settings.json. JSON Error Message: Unexpected character (']' (code 93)): expected a value\n at [Source: (File); line: 91, column: 3] (through reference chain: adris.altoclef.Settings["areasToProtect"]).\n JSON Error STACK TRACE:\n\n\nat:\nadris.altoclef.Debug.logError(Debug.java:51)\nadris.altoclef.Settings.load(Settings.java:394)\nadris.altoclef.AltoClef.reloadModSettings(AltoClef.java:299)\nadris.altoclef.commands.ReloadSettingsCommand.call(ReloadSettingsCommand.java:15)\nadris.altoclef.commandsystem.Command.run(Command.java:30)\nadris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:41)\nadris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:49)\nadris.altoclef.StaticMixinHookups.onChat(StaticMixinHookups.java:53)\nnet.minecraft.class_746.handler$zzf000$sendChatMessage(class_746.java:1271)\nnet.minecraft.class_746.method_3142(class_746.java)\nnet.minecraft.class_437.method_25425(class_437.java:376)\nnet.minecraft.class_437.method_25427(class_437.java:369)\nnet.minecraft.class_408.method_25404(class_408.java:101)\nnet.minecraft.class_309.method_1454(class_309.java:374)\nnet.minecraft.class_437.method_25412(class_437.java:490)\nnet.minecraft.class_309.method_1466(class_309.java:370)\nnet.minecraft.class_309.method_22678(class_309.java:462)\nnet.minecraft.class_1255.execute(class_1255.java:101)\nnet.minecraft.class_309.method_22676(class_309.java:462)\norg.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)\norg.lwjgl.system.JNI.invokeV(Native Method)\norg.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)\ncom.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)\nnet.minecraft.class_1041.method_15998(class_1041.java:310)\nnet.minecraft.class_310.method_1523(class_310.java:1137)\nnet.minecraft.class_310.method_1514(class_310.java:728)\nnet.minecraft.client.main.Main.main(Main.java:217)\njava.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\njava.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)\njava.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\njava.base/java.lang.reflect.Method.invoke(Method.java:567)\nnet.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)\nnet.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)\nnet.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)\n§r
[21:04:17] [Render thread/INFO]: [STDERR]: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character (']' (code 93)): expected a value
 at [Source: (File); line: 91, column: 3] (through reference chain: adris.altoclef.Settings["areasToProtect"])
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1714)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.Settings.load(Settings.java:392)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.AltoClef.reloadModSettings(AltoClef.java:299)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commands.ReloadSettingsCommand.call(ReloadSettingsCommand.java:15)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commandsystem.Command.run(Command.java:30)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:41)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.commandsystem.CommandExecutor.execute(CommandExecutor.java:49)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at adris.altoclef.StaticMixinHookups.onChat(StaticMixinHookups.java:53)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.handler$zzf000$sendChatMessage(class_746.java:1271)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_746.method_3142(class_746.java)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25425(class_437.java:376)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25427(class_437.java:369)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_408.method_25404(class_408.java:101)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1454(class_309.java:374)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:490)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_1466(class_309.java:370)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22678(class_309.java:462)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:101)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_309.method_22676(class_309.java:462)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:172)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1137)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:728)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[21:04:17] [Render thread/INFO]: [STDERR]: Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (']' (code 93)): expected a value
 at [Source: (File); line: 91, column: 4]
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2621)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:856)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
[21:04:17] [Render thread/INFO]: [STDERR]: 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
[21:04:17] [Render thread/INFO]: [STDERR]: 	... 36 more
[21:04:17] [Render thread/INFO]: [CHAT] §2§l§o[Alto Clef] §rReload successful!
[21:04:21] [Render thread/INFO]: [STDOUT]: ALTO CLEF: CHUNKS RESET
[21:04:23] [Render thread/INFO]: Stopping!

**Comment by walksanator** [comment]
Remove the comma after the last }
That should fix it

**Comment by hejgustav** [comment]
Fixed. Thank you.
