### ISSUE TITLE
Game Crashed with java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by YocyCraft** [gaucho-matrero/altoclef#316]
is this mod conflict with other mods?
crash report:
---- Minecraft Crash Report ----
// Don't do that.

Time: 2022/11/29 上午12:41
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_6880 net.minecraft.class_638.method_23753(net.minecraft.class_2338)'
	at adris.altoclef.util.helpers.WorldHelper.canReach(WorldHelper.java:251)
	at adris.altoclef.util.helpers.WorldHelper.canBreak(WorldHelper.java:206)
	at adris.altoclef.tasks.resources.MineAndCollectTask$MineOrCollectTask.lambda$getClosestTo$0(MineAndCollectTask.java:187)
	at adris.altoclef.trackers.BlockTracker$PosCache.getNearest(BlockTracker.java:562)
	at adris.altoclef.trackers.BlockTracker.getNearestTracking(BlockTracker.java:227)
	at adris.altoclef.tasks.resources.MineAndCollectTask$MineOrCollectTask.getClosestTo(MineAndCollectTask.java:185)
	at adris.altoclef.tasks.AbstractDoToClosestObjectTask.onTick(AbstractDoToClosestObjectTask.java:71)
	at adris.altoclef.tasks.resources.MineAndCollectTask$MineOrCollectTask.onTick(MineAndCollectTask.java:225)
	at adris.altoclef.tasksystem.Task.tick(Task.java:33)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.chains.SingleTaskChain.onTick(SingleTaskChain.java:38)
	at adris.altoclef.chains.UserTaskChain.onTick(UserTaskChain.java:54)
	at adris.altoclef.tasksystem.TaskChain.tick(TaskChain.java:18)
	at adris.altoclef.tasksystem.TaskRunner.tick(TaskRunner.java:39)
	at adris.altoclef.AltoClef.onClientTick(AltoClef.java:198)
	at adris.altoclef.AltoClef.lambda$onInitializeLoad$7(AltoClef.java:166)
	at adris.altoclef.eventbus.Subscription.accept(Subscription.java:15)
	at adris.altoclef.eventbus.EventBus.publish(EventBus.java:47)
	at net.minecraft.class_310.handler$zzk000$clientTick(class_310.java:3475)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at adris.altoclef.util.helpers.WorldHelper.canReach(WorldHelper.java:251)
	at adris.altoclef.util.helpers.WorldHelper.canBreak(WorldHelper.java:206)
	at adris.altoclef.tasks.resources.MineAndCollectTask$MineOrCollectTask.lambda$getClosestTo$0(MineAndCollectTask.java:187)
	at adris.altoclef.trackers.BlockTracker$PosCache.getNearest(BlockTracker.java:562)
	at adris.altoclef.trackers.BlockTracker.getNearestTracking(BlockTracker.java:227)
	at adris.altoclef.tasks.resources.MineAndCollectTask$MineOrCollectTask.getClosestTo(MineAndCollectTask.java:185)
	at adris.altoclef.tasks.AbstractDoToClosestObjectTask.onTick(AbstractDoToClosestObjectTask.java:71)
	at adris.altoclef.tasks.resources.MineAndCollectTask$MineOrCollectTask.onTick(MineAndCollectTask.java:225)
	at adris.altoclef.tasksystem.Task.tick(Task.java:33)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.tasksystem.Task.tick(Task.java:54)
	at adris.altoclef.chains.SingleTaskChain.onTick(SingleTaskChain.java:38)
	at adris.altoclef.chains.UserTaskChain.onTick(UserTaskChain.java:54)
	at adris.altoclef.tasksystem.TaskChain.tick(TaskChain.java:18)
	at adris.altoclef.tasksystem.TaskRunner.tick(TaskRunner.java:39)
	at adris.altoclef.AltoClef.onClientTick(AltoClef.java:198)
	at adris.altoclef.AltoClef.lambda$onInitializeLoad$7(AltoClef.java:166)
	at adris.altoclef.eventbus.Subscription.accept(Subscription.java:15)
	at adris.altoclef.eventbus.EventBus.publish(EventBus.java:47)
	at net.minecraft.class_310.handler$zzk000$clientTick(class_310.java:3475)

-- Affected level --
Details:
	All players: 1 total; [class_746['hanhengrui'/229, l='ClientLevel', x=1.50, y=122.00, z=35.26]]
	Chunk stats: 1024, 581
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,124,0), Section: (at 0,12,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2306 game time, 2306 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, AnvilCraft-0.4.1-1.18.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3354181712 bytes (3198 MiB) / 5800722432 bytes (5532 MiB) up to 5800722432 bytes (5532 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: whiskey Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9b41
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8984
	Graphics card #1 name: NVIDIA GeForce MX250
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1d13
	Graphics card #1 versionInfo: DriverVersion=26.21.14.4112
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28049.89
	Virtual memory used (MB): 24696.22
	Swap memory total (MB): 11832.60
	Swap memory used (MB): 487.38
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx5529m
	Fabric Mods: 
		altoclef: Alto Clef 0.4.1a
		architectury: Architectury 3.2.51
		baritone: Baritone 1.18.2
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.11
		geckolib3: Geckolib 3.0.33
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lithium: Lithium 0.7.6
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		org_joml_joml: joml 1.10.2
		phosphor: Phosphor 0.8.1
		roughlyenoughitems: Roughly Enough Items 7.1.356
		sodium: Sodium 0.4.0-alpha5+build.9
	Launched Version: 1.18.1-Fabric 0.12.11
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.8984, Intel
	Window size: 1920x986
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/AnvilCraft-0.4.1-1.18.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['hanhengrui'/229, l='ServerLevel[AITest]', x=1.50, y=122.00, z=35.26]]
	Data Packs: vanilla, Fabric Mods

**Comment by JustaSqu1d** [comment]
Alto Clef version 0.4.1a supports 1.18.2, not 1.18.1.

**Comment by YocyCraft** [comment]
solved thanks
then my AI fell into lava when building nether portal lol

**Comment by JustaSqu1d** [comment]
> solved thanks then my AI fell into lava when building nether portal lol

Could you close this issue then?
