### ISSUE TITLE
The game crash when use the gamer (@gamer) command

### ISSUE THREAD

**Issue by notguoxin** [gaucho-matrero/altoclef#346]
## Steps to Reproduce (as best as you can)
Start a world , run @gamer, (the bot do its stuff) and it crash!
## Expected Behavior
Beat the game
## Actual Behavior (What lead to the bot getting permanently stuck)
The game crash
## Crashlogs and Screenshots (if applicable)
````
[12:01:46] [pool-2-thread-3/ERROR]: Uncaught exception in thread "pool-2-thread-3"
java.lang.NoSuchMethodError: 'double net.minecraft.class_2338.method_19770(net.minecraft.class_2374)'
	at adris.altoclef.trackers.BlockTracker$PosCache.lambda$smartPurge$1(BlockTracker.java:652) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.util.helpers.StlHelper.lambda$compareValues$0(StlHelper.java:11) ~[altoclef-0.4.0.jar:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1307) ~[?:?]
	at java.util.ArrayList.sort(ArrayList.java:1721) ~[?:?]
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392) ~[?:?]
	at java.util.stream.DistinctOps$1$2.end(DistinctOps.java:168) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at adris.altoclef.trackers.BlockTracker$PosCache.smartPurge(BlockTracker.java:653) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.trackers.BlockTracker.rescanWorld(BlockTracker.java:371) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.trackers.BlockTracker.lambda$update$3(BlockTracker.java:309) ~[altoclef-0.4.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:01:46] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_6880 net.minecraft.class_638.method_23753(net.minecraft.class_2338)'
	at adris.altoclef.util.helpers.WorldHelper.canReach(WorldHelper.java:251) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.util.helpers.WorldHelper.canBreak(WorldHelper.java:206) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.tasks.speedrun.BeatMinecraft2Task.lambda$onTick$8(BeatMinecraft2Task.java:310) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.trackers.BlockTracker$PosCache.anyFound(BlockTracker.java:466) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.trackers.BlockTracker.anyFound(BlockTracker.java:193) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.tasks.speedrun.BeatMinecraft2Task.onTick(BeatMinecraft2Task.java:310) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.tasksystem.Task.tick(Task.java:33) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.chains.SingleTaskChain.onTick(SingleTaskChain.java:38) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.chains.UserTaskChain.onTick(UserTaskChain.java:54) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.tasksystem.TaskChain.tick(TaskChain.java:18) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.tasksystem.TaskRunner.tick(TaskRunner.java:39) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.AltoClef.onClientTick(AltoClef.java:198) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.AltoClef.lambda$onInitializeLoad$7(AltoClef.java:166) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.eventbus.Subscription.accept(Subscription.java:15) ~[altoclef-0.4.0.jar:?]
	at adris.altoclef.eventbus.EventBus.publish(EventBus.java:47) ~[altoclef-0.4.0.jar:?]
	at net.minecraft.class_310.handler$zzk000$altoclef$clientTick(class_310.java:3475) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1086) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[12:01:46] [Server thread/INFO]: Stopping server
[12:01:46] [Server thread/INFO]: Saving players
[12:01:46] [Server thread/INFO]: <ACCESS TOKEN> lost connection: Disconnected
[12:01:46] [Server thread/INFO]: <ACCESS TOKEN> left the game
[12:01:46] [Server thread/INFO]: Stopping singleplayer server as player logged out
[12:01:46] [Server thread/INFO]: Saving worlds
[12:01:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[12:01:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[12:01:47] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[12:01:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[12:01:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:01:47] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:01:47] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 5/1/23, 12:01 PM
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_6880 net.minecraft.class_638.method_23753(net.minecraft.class_2338)'
	at adris.altoclef.util.helpers.WorldHelper.canReach(WorldHelper.java:251)
	at adris.altoclef.util.helpers.WorldHelper.canBreak(WorldHelper.java:206)
	at adris.altoclef.tasks.speedrun.BeatMinecraft2Task.lambda$onTick$8(BeatMinecraft2Task.java:310)
	at adris.altoclef.trackers.BlockTracker$PosCache.anyFound(BlockTracker.java:466)
	at adris.altoclef.trackers.BlockTracker.anyFound(BlockTracker.java:193)
	at adris.altoclef.tasks.speedrun.BeatMinecraft2Task.onTick(BeatMinecraft2Task.java:310)
	at adris.altoclef.tasksystem.Task.tick(Task.java:33)
	at adris.altoclef.chains.SingleTaskChain.onTick(SingleTaskChain.java:38)
	at adris.altoclef.chains.UserTaskChain.onTick(UserTaskChain.java:54)
	at adris.altoclef.tasksystem.TaskChain.tick(TaskChain.java:18)
	at adris.altoclef.tasksystem.TaskRunner.tick(TaskRunner.java:39)
	at adris.altoclef.AltoClef.onClientTick(AltoClef.java:198)
	at adris.altoclef.AltoClef.lambda$onInitializeLoad$7(AltoClef.java:166)
	at adris.altoclef.eventbus.Subscription.accept(Subscription.java:15)
	at adris.altoclef.eventbus.EventBus.publish(EventBus.java:47)
	at net.minecraft.class_310.handler$zzk000$altoclef$clientTick(class_310.java:3475)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at adris.altoclef.util.helpers.WorldHelper.canReach(WorldHelper.java:251)
	at adris.altoclef.util.helpers.WorldHelper.canBreak(WorldHelper.java:206)
	at adris.altoclef.tasks.speedrun.BeatMinecraft2Task.lambda$onTick$8(BeatMinecraft2Task.java:310)
	at adris.altoclef.trackers.BlockTracker$PosCache.anyFound(BlockTracker.java:466)
	at adris.altoclef.trackers.BlockTracker.anyFound(BlockTracker.java:193)
	at adris.altoclef.tasks.speedrun.BeatMinecraft2Task.onTick(BeatMinecraft2Task.java:310)
	at adris.altoclef.tasksystem.Task.tick(Task.java:33)
	at adris.altoclef.chains.SingleTaskChain.onTick(SingleTaskChain.java:38)
	at adris.altoclef.chains.UserTaskChain.onTick(UserTaskChain.java:54)
	at adris.altoclef.tasksystem.TaskChain.tick(TaskChain.java:18)
	at adris.altoclef.tasksystem.TaskRunner.tick(TaskRunner.java:39)
	at adris.altoclef.AltoClef.onClientTick(AltoClef.java:198)
	at adris.altoclef.AltoClef.lambda$onInitializeLoad$7(AltoClef.java:166)
	at adris.altoclef.eventbus.Subscription.accept(Subscription.java:15)
	at adris.altoclef.eventbus.EventBus.publish(EventBus.java:47)
	at net.minecraft.class_310.handler$zzk000$altoclef$clientTick(class_310.java:3475)

-- Affected level --
Details:
	All players: 1 total; [class_746['<ACCESS TOKEN>'/233, l='ClientLevel', x=21.65, y=76.00, z=18.61]]
	Chunk stats: 529, 293
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,81,0), Section: (at 0,1,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4917 game time, 4917 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1815247120 bytes (1731 MiB) / 3688890368 bytes (3518 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5912
	Graphics card #0 versionInfo: DriverVersion=31.0.101.2121
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14799.58
	Virtual memory used (MB): 12582.98
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 2294.16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	Fabric Mods: 
		altoclef: Alto Clef 0.4.1a
		baritone: Baritone 1.18.2
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18
	Launched Version: 1.18
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 630 GL version 3.2.0 - Build 31.0.101.2121, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['<ACCESS TOKEN>'/233, l='ServerLevel[New World]', x=21.65, y=76.00, z=18.61]]
	Data Packs: vanilla, Fabric Mods
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Admin\Desktop\MultiMC\instances\1.18\.minecraft\crash-reports\crash-2023-05-01_12.01.47-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
````
## Other mods (if applicable)

- altoclef-0.4.0.jar
- baritone-unoptimized-fabric-1.18.2.jar
- fabric-api-0.44.0+1.18.jar

### Discord username (if you want updates)
`iwastesting#2031`
PS: I don't usually open discord
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by TheBlueBurger** [comment]
You are using a 1.18.2 build of altoclef, upgrade to 1.18.2 and it should work

**Comment by notguoxin** [comment]
fixed, I downloaded the wrong version.

**Comment by plakiiskute** [comment]
wait what?
1.18.2<1.18.2 pls help
